module.exports = {
  positions: {
    starting: [
      'QB',
      'RB1',
      'RB2',
      'WR1',
      'WR2',
      'TE',
      'FLEX',
      'D/ST',
      'K',
    ],
    bench: [
      'Bench1',
      'Bench2',
      'Bench3',
      'Bench4',
      'Bench5',
      'Bench6',
      'Bench7',
    ],
  },
  weeks: [
    { value: 1, children: 'Week One' },
    { value: 2, children: 'Week Two' },
    { value: 3, children: 'Week Three' },
    { value: 4, children: 'Week Four' },
    { value: 5, children: 'Week Five' },
    { value: 6, children: 'Week Six' },
    { value: 7, children: 'Week Seven' },
    { value: 8, children: 'Week Eight' },
    { value: 9, children: 'Week Nine' },
    { value: 10, children: 'Week Ten' },
    { value: 11, children: 'Week Eleven' },
    { value: 12, children: 'Week Twelve' },
    { value: 13, children: 'Week Thirteen' },
    { value: 14, children: 'Week Fourteen' },
    { value: 15, children: 'Week Fifteen' },
    { value: 16, children: 'Week Sixteen' },
    { value: 17, children: 'Week Seventeen' },
  ],
};
